In [1]:
import pandas as pd    


data = pd.read_csv("./Gamma Data/cycle_352.csv")

data

,Step,time,passes,recirculated,discarded,keff,keff_relative_uncertainty,keff_absolute_uncertainty,neutrons_per_cycle,power_normalization_value,DEM_step_increment,threshold_fuel,time_step
0,0,0.000,0.000000,NaN,NaN,NaN,NaN,NaN,50000,10000000.0,1,72,0.000
1,1,12.512,0.050008,1563.0,382.0,0.993459,0.000587,0.000583,50000,10000000.0,1,72,0.000
2,2,25.024,0.100016,1563.0,358.0,0.996394,0.000563,0.000561,50000,10000000.0,1,72,12.512
3,3,37.536,0.150024,1563.0,389.0,0.996537,0.000554,0.000552,50000,10000000.0,1,72,12.512
4,4,50.048,0.200032,1563.0,388.0,1.000258,0.000589,0.000590,50000,10000000.0,1,72,12.512
...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,348,4354.176,17.402782,1563.0,326.0,1.015423,0.000543,0.000551,50000,10000000.0,1,72,12.512
349,349,4366.688,17.452790,1563.0,315.0,1.015630,0.000571,0.000580,50000,10000000.0,1,72,12.512
350,350,4379.200,17.502798,1563.0,320.0,1.015569,0.000545,0.000554,50000,10000000.0,1,72,12.512
351,351,4391.712,17.552806,1563.0,327.0,1.016668,0.000547,0.000556,50000,10000000.0,1,72,12.512
352,352,4404.224,17.602814,1563.0,341.0,1.015148,0.000559,0.000567,50000,10000000.0,1,72,12.512