In [1]:
import pandas as pd

In [2]:
pd.read_csv('https://data.cdc.gov/resource/fcqm-xrf4.csv')

,year,date,statefips,countyfips,ctfips,latitude,longitude,ds_pm_pred,ds_pm_stdd
0,2011,27JUN2011,17,17031,17031804804,41.99653,-88.12764,7.105345,2.032659
1,2011,27JUN2011,17,17031,17031804805,42.02006,-88.12907,7.135416,2.124936
2,2011,27JUN2011,17,17031,17031804806,42.00872,-88.13638,7.058703,2.109426
3,2011,27JUN2011,17,17031,17031804807,42.01039,-88.12000,7.143073,2.076395
4,2011,27JUN2011,17,17031,17031804808,42.02201,-88.10001,7.247980,2.087128
...,...,...,...,...,...,...,...,...,...
995,2011,27JUN2011,17,17091,17091010602,41.18515,-87.86349,7.102010,2.293808
996,2011,27JUN2011,17,17091,17091010701,41.18275,-87.81214,7.093158,2.361559
997,2011,27JUN2011,17,17091,17091010702,41.14883,-87.81685,7.196685,2.416971
998,2011,27JUN2011,17,17091,17091010800,41.14833,-87.70957,7.260982,2.364548
999,2011,27JUN2011,17,17091,17091010900,41.20367,-87.58562,7.360361,2.346339